### ISSUE TITLE
Where is source code for Microsoft implementation for Machine Learning Algorithms? 

### ISSUE THREAD

**Issue by heathyates** [Azure/Azure-MachineLearning-DataScience#15]
Where is the source code for the standard Machine Learning algorithms like you can use in java for [WEKA](http://www.cs.waikato.ac.nz/ml/weka/)? I am a .NET developer and a graduate student. I would like to use Microsoft tools both for software development and algorithm research in Machine Learning, but I have not seen where, if anywhere, the source code is for your standard Machine Learning algorithms (C4.5, I3, Forest, SVM, K-Means, Knn, and etc). I think this is a completely valid question especially in the light of open source software releases by other major companies such as Google.

**Comment by zooba** [comment]
I don't think it's published or open source. You'd be best to go to the ML Studio web site and find a contact link there - this GitHub page is only going to reach the people working on the Python wrapper around the management APIs. It doesn't include any of the algorithmic code at all.

**Comment by heathyates** [comment]
Thanks. I appreciate the response.

**Comment by ktakeda1** [comment]
And check out our new open source distributed ML toolkit too - http://blogs.technet.com/b/inside_microsoft_research/archive/2015/11/12/microsoft-open-sources-distributed-machine-learning-toolkit-efficient-big-data-research.aspx

**Comment by zooba** [comment]
@heathyates  I apologise for my response - it seems you are on the correct GitHub repo. I'm not supposed to be subscribed to it, so I confused it for one that I _am_ subscribed to.

**Comment by heathyates** [comment]
@ktakeda1 @zooba No worries. Thanks for your reply. Any word on when or if any code will be added to this repository for ML algorithms?
