### ISSUE TITLE
JupyterHub extension does not deploy

### ISSUE THREAD

**Issue by TopperKain** [Azure/Azure-MachineLearning-DataScience#22]
Attempting to deploy the DSVM for Linux with the JuypterHub extension at https://github.com/Azure/Azure-MachineLearning-DataScience/tree/master/Data-Science-Virtual-Machine/Linux/extensions/JupyterHub does not succeed.

Clicking on the "Deploy to Azure" link and filling out the information on the first page results in the following error:

The template deployment 'a001b153-1426-4670-8d9c-3857dfc160f8' is not valid according to the validation procedure. The tracking id is 'cc596c6e-8cdc-4adb-8939-cdd7801b6ab2'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.

**Comment by paulshealy1** [comment]
JupyterHub is now built into the Linux DSVM image, so you should deploy without the extension.
