### ISSUE TITLE
Jupyter Notebook / Hub non-functional upon deployment

### ISSUE THREAD

**Issue by TopperKain** [Azure/Azure-MachineLearning-DataScience#23]
After deploying a DSVM for Linux via the Azure portal, I remoted into the machine via the x2go client. On the desktop, I double clicked the Jupyter icon which took me to https://localhost:8000/hub/login.  The login screen appeared, but after logging in I was greeted by at 500 Internal Server Error.

The same issue occurs trying to access the VM remotely (via chrome on my local desktop.)

**Comment by paulshealy1** [comment]
That's not expected. Can you paste the JupyterHub logs from /var/log/jupyterhub.log?

**Comment by TopperKain** [comment]
Attached the log.
[jupyterhub.log.txt](https://github.com/Azure/Azure-MachineLearning-DataScience/files/422735/jupyterhub.log.txt)

**Comment by paulshealy1** [comment]
JupyterHub is looking for a user 'topper' that doesn't exist on the system. Adding it and restarting the jupyterhub service should fix the issue.

**Comment by TopperKain** [comment]
This ended up being a case-sensitivity issue. I created this as a throwaway VM with the admin named "Topper", but it looks like jupyterhub was configured to look for a user named "topper". Creating that user made the error go away. In the future I can presumably use just lowercase local users.

**Comment by svzdvdoptum** [comment]
I think that's an issue: usernames must be case sensitive... It's discussed here: https://github.com/jupyterhub/jupyterhub/issues/1671

**Comment by paulshealy1** [comment]
I'll close this issue as you found a resolution.
