### ISSUE TITLE
The Criteo Dataset is not Accessible

### ISSUE THREAD

**Issue by dedcode** [Azure/Azure-MachineLearning-DataScience#26]
Trying to run

```
CREATE DATABASE IF NOT EXISTS criteo;
DROP TABLE IF EXISTS criteo.criteo_count;
CREATE TABLE criteo.criteo_count (
col1 string,col2 double,col3 double,col4 double,col5 double,col6 double,col7 double,col8 double,col9 double,col10 double,col11 double,col12 double,col13 double,col14 double,col15 string,col16 string,col17 string,col18 string,col19 string,col20 string,col21 string,col22 string,col23 string,col24 string,col25 string,col26 string,col27 string,col28 string,col29 string,col30 string,col31 string,col32 string,col33 string,col34 string,col35 string,col36 string,col37 string,col38 string,col39 string,col40 string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE LOCATION 'wasb://azuremlsampleexperiments.blob.core.windows.net/raw/count';
```

and getting
`Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:Got exception: org.apache.hadoop.fs.azure.AzureException org.apache.hadoop.fs.azure.AzureException: Container criteo in account azuremlsampleexperiments.blob.core.windows.net not found, and we can't create it using anoynomous credentials, and no credentials found for them in the configuration.)`
Am I missing something in the tutorial ?

**Comment by deguhath** [comment]
I think you will have to download and save the text data in your blob/container first, and then use the exact same container to load data into Hive.
