### ISSUE TITLE
Data Science VM not available in Azure CSP subscriptions

### ISSUE THREAD

**Issue by wlodekbielski** [Azure/Azure-MachineLearning-DataScience#41]
We are providing Azure to Customer as Cloud Solution Partner. They are very much interested in both Windows/Linux Data Science VMs - however, it seems to be impossible to deploy images to CSP subscriptions.
This is really a pain point for us, and I could not imagine a reason why this shouldn't be allowed by Microsoft.
When in Azure Marketplace, and trying to deploy - it says "Not allowed" when I want to deploy to CSP subscription.
As our all data sources are under this subscription, it would make no sense for us to create DS VM in another one.

Looking very much forward to help / suggestion here.
Wlodek

**Comment by gopitk** [comment]
Sorry you are having this issue. Have you opened a support ticket with Azure from your Azure portal? If so, please let us know the ticket number. We will see if we can followup and see if there is something that can be done to remove this limitation.

**Comment by gopitk** [comment]
We have just published a new “SKU plan” on the Linux DSVM to allow Cloud Service Partners like you to create Linux DSVM. 

You will see a SKU on Portal titled “Linux Data Science Virtual Machine (BYOL/CSP)”. (See pasted image)

Can you please try this and let us know. If it works we will do the same with Windows DSVM also. 
![linuxdsvmbyol](https://cloud.githubusercontent.com/assets/12767235/24277147/88698ed4-0ff8-11e7-81f1-e9cef22dfbd3.png)

**Comment by wlodekbielski** [comment]
Thanks a lot!
I do confirm that it works now - and I can deploy Linux Data Science VM (BYOL/CSP) to CSP successfully!

Just to let you know, sometimes I get stucked on last step:
![vmconfpartfail](https://cloud.githubusercontent.com/assets/21252231/24290953/4a752982-1087-11e7-82f1-fd60f0cad12f.png)

But after retrying it some more times, finally it passed validation:
![vmea](https://cloud.githubusercontent.com/assets/21252231/24291030/8cbd2060-1087-11e7-91e5-e3f477c1f727.png)

I very much appreciate your effort!
It would be also great if you could publish similar BYOL/CSP template for Windows DS VM as well.
