### ISSUE TITLE
Both JupyterLab and R-studio server have authentication errors

### ISSUE THREAD

**Issue by omri374** [Azure/Azure-MachineLearning-DataScience#54]
Hi,
I set up a DSVM (ubuntu) and logged into JupyterLab, I got an 'Insecure Connection' message on my browser with the following text:

`my-dsvm.westeurope.cloudapp.azure.com:8000 uses an invalid security certificate. The certificate is not trusted because it is self-signed. The certificate is not valid for the name my-dsvm-r.westeurope.cloudapp.azure.com. Error code: SEC_ERROR_UNKNOWN_ISSUER`

On R-studio-server, I get a message saying 'The connection is not secure. Login entered here may be compromised' and a link to here:
https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox?as=u&utm_source=inproduct

Is there an option to use r studio server with https instead of http?

I'm using Firefox but this occurs on Chrome as well.

Thanks! keep up the good work.
Omri

**Comment by gopitk** [comment]
Yes. The certificates in Jupyter/Jupyterlab are self signed by default,. You can install a real cert from a cert authority for your server. Regardign R studio server, what we have is the community edition. Rstudio server requires a paid version to run SSL. You may be able to do SSH tunnelling.
