### ISSUE TITLE
azureml module is unstable

### ISSUE THREAD

**Issue by arpitvw** [Azure/Azure-MachineLearning-DataScience#58]
when i am importing 
from azureml.train.automl import AutoMLRunx sometimes its getting imported and sometime i amgetting error ImportError: cannot import name 'AutoMLRunx'

same with reading file from blob ,sometime i can run the code successfully but sometime it gives error while read blob file itself
"pipeline is broken"

all the module are behaving weird

**Comment by gopitk** [comment]
@arpitvw - Which example you running? This repo is not the latest azureml model. Please try the samples in https://github.com/Azure/MachineLearningNotebooks and provide feedback on issues within that repo. I will close this issue here.
